/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: f474e1aaa52782172e6ece3066013848)
interface __BaseEnv_Env {
	COMMENTS_DB: D1Database;
	ASSETS: Fetcher;
	COMMENTS_HASH_SALT: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./dist/_worker.js/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "COMMENTS_HASH_SALT">> {}
}
