/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 107ed7cea45efc562f00f746fef765eb)
interface __BaseEnv_Env {
	COMMENTS_DB: D1Database;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./dist/_worker.js/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
