/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 479ddae4c682be9182fa1ac13efdf895)
interface __BaseEnv_Env {
	COMMENTS_DB: D1Database;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
